#!/bin/sh
#
# Startup script for MaNGOLin
# We need to ensure we startup in the correct working directory
APPHOME=/usr/share/mangolin
# Run our jar file
cd $APPHOME
java -Xmx256m -jar MaNGOLin.jar "$@" &

