/*
 * Copyright (C) 2007-2013 Alistair Neil, <info@dazzleships.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License Version 2 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package client;

import lib.Localisation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 *
 * @author Alistair Neil, <info@dazzleships.net>
 */
public class CommandsFrame extends javax.swing.JFrame {

    private MangosSql ms = null;
    private Localisation local;

    public CommandsFrame(MangosSql ms) {
        initComponents();
        this.ms = ms;
        this.local = new Localisation("lang/MessagesBundle");
        updateCommandTable();
    }

    private void updateCommandTable() {
        String query = "select name, security from command";
        if (!jTextFilter.getText().isEmpty()) {
            query += " where name like '%" + jTextFilter.getText() + "%'";
        }
        ms.setStatement("commands");
        dbTableCommand.getModel().setResultSet(ms.executeQuery(query));
        dbTableCommand.getModel().setPrimaryKey("name");
        dbTableCommand.enableNumericReplacement("security",
                local.getStrings("gm_player", "gm_mod", "gm_games", "gm_admin", "gm_god"));
        dbTableCommand.getModel().refreshTableContents();
        dbTableCommand.autoAdjustRowHeight();
        jTextCommandDesc.setText("");
        if (dbTableCommand.getRowCount() > 0) {
            dbTableCommand.setRowSelectionInterval(0, 0);
            updateCommandDesc();
        }
    }

    private void updateCommandDesc() {

        String name = (String) dbTableCommand.getSelectedItem(0);
        try {
            ms.executeQuery("select help from command where name = '" + name + "'");
            ms.getResultSet().next();
            jTextCommandDesc.setText(ms.getResultSet().getString(1));
        } catch (SQLException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextCommandDesc = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        dbTableCommand = new lib.DBJTableBean();
        jLabel1 = new javax.swing.JLabel();
        jTextFilter = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/MessagesBundle"); // NOI18N
        setTitle(bundle.getString("title_cmdsref")); // NOI18N
        setResizable(false);

        jButtonClose.setText(bundle.getString("butt_close")); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextCommandDesc.setEditable(false);
        jTextCommandDesc.setLineWrap(true);
        jTextCommandDesc.setRows(5);
        jTextCommandDesc.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextCommandDesc);

        dbTableCommand.setAutoColumnEnabled(true);
        dbTableCommand.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dbTableCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbTableCommandMouseClicked(evt);
            }
        });
        dbTableCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dbTableCommandKeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(dbTableCommand);

        jLabel1.setText(bundle.getString("lab_filter")); // NOI18N

        jTextFilter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFilterCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbTableCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbTableCommandMouseClicked
        updateCommandDesc();
}//GEN-LAST:event_dbTableCommandMouseClicked

    private void dbTableCommandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dbTableCommandKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            updateCommandDesc();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            updateCommandDesc();
        }
}//GEN-LAST:event_dbTableCommandKeyReleased

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jTextFilterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFilterCaretUpdate
        updateCommandTable();
    }//GEN-LAST:event_jTextFilterCaretUpdate

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lib.DBJTableBean dbTableCommand;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextCommandDesc;
    private javax.swing.JTextField jTextFilter;
    // End of variables declaration//GEN-END:variables
}
