/*
 * Copyright (C) 2007-2013 Alistair Neil, <info@dazzleships.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License Version 2 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package client;

import lib.GlobalFunctions;
import lib.SimpleINI;

/**
 *
 * @author Alistair Neil, <info@dazzleships.net>
 */
public final class PrefsDialog extends javax.swing.JDialog {

    public static final int CANCEL = 0;
    public static final int APPLY = 1;
    public static final int RESET = 2;
    private final GlobalFunctions gf = GlobalFunctions.getInstance();
    private SimpleINI simpleIni = null;

    /**
     * Creates a preferences editor dialog
     *
     * @param parent Parent Frame
     * @param simpleini ini object to be modified
     */
    public PrefsDialog(java.awt.Frame parent, SimpleINI simpleini) {
        super(parent, true);
        simpleIni = simpleini;
        initComponents();
        loadPreferences();
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * Set whether to use system tray or not
     *
     * @param enabled
     */
    public void setTrayEnabled(boolean enabled) {

        if (!enabled) {
            jCheckDisableTray.setEnabled(enabled);
        }
    }

    /**
     * Load the preferences
     */
    private void loadPreferences() {
        simpleIni.setGroup("GUI");
        jCheckDisableTray.setSelected(simpleIni.getBoolValue("disabletray", true));
        jCheckHideTray.setSelected(simpleIni.getBoolValue("hidetray", false));
        jCheckUpdates.setSelected(simpleIni.getBoolValue("checkupdate", true));
        String theme = simpleIni.getStringValue("theme", "System");
        jComboBoxTheme.setSelectedItem(theme);
        if (gf.isLinux()) {
            jSpinnerFontSize.setEnabled(!theme.contentEquals("System"));
        }
        jSpinnerFontSize.setValue(simpleIni.getIntegerValue("fontsize", 9));
        jCheckWindowDec.setSelected(simpleIni.getBoolValue("windowdec", true));
        jCheckWindowDec.setEnabled(!(theme.contentEquals("System") | theme.contentEquals("Nimbus")));
    }

    /**
     * Save preferences
     */
    public void updatePreferences() {
        simpleIni.setGroup("GUI");
        simpleIni.setValue("windowdec", jCheckWindowDec.isSelected());
        simpleIni.setValue("disabletray", jCheckDisableTray.isSelected());
        simpleIni.setValue("hidetray", jCheckHideTray.isSelected());
        simpleIni.setValue("checkupdate", jCheckUpdates.isSelected());
        simpleIni.setValue("theme", jComboBoxTheme.getSelectedItem());
        simpleIni.setValue("fontsize", (Integer) jSpinnerFontSize.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelGeneralPrefs = new javax.swing.JPanel();
        jCheckHideTray = new javax.swing.JCheckBox();
        jCheckUpdates = new javax.swing.JCheckBox();
        jCheckDisableTray = new javax.swing.JCheckBox();
        jPanelThemes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTheme = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerFontSize = new javax.swing.JSpinner();
        jCheckWindowDec = new javax.swing.JCheckBox();
        jButtonCancel = new javax.swing.JButton();
        jButtonApply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setFont(jPanel1.getFont().deriveFont(jPanel1.getFont().getStyle() | java.awt.Font.BOLD, jPanel1.getFont().getSize()+3));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/MessagesBundle"); // NOI18N
        jPanelGeneralPrefs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("title_settings"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jPanel1.getFont(), jPanel1.getForeground())); // NOI18N
        jPanelGeneralPrefs.setFont(jPanelGeneralPrefs.getFont().deriveFont(jPanelGeneralPrefs.getFont().getStyle() | java.awt.Font.BOLD, jPanelGeneralPrefs.getFont().getSize()+3));

        jCheckHideTray.setText(bundle.getString("check_hide")); // NOI18N
        jCheckHideTray.setToolTipText(bundle.getString("check_hide")); // NOI18N

        jCheckUpdates.setSelected(true);
        jCheckUpdates.setText(bundle.getString("check_updates")); // NOI18N
        jCheckUpdates.setToolTipText(bundle.getString("check_updates")); // NOI18N

        jCheckDisableTray.setText(bundle.getString("check_tray")); // NOI18N
        jCheckDisableTray.setToolTipText(bundle.getString("check_tray")); // NOI18N

        javax.swing.GroupLayout jPanelGeneralPrefsLayout = new javax.swing.GroupLayout(jPanelGeneralPrefs);
        jPanelGeneralPrefs.setLayout(jPanelGeneralPrefsLayout);
        jPanelGeneralPrefsLayout.setHorizontalGroup(
            jPanelGeneralPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralPrefsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeneralPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckDisableTray)
                    .addComponent(jCheckUpdates)
                    .addComponent(jCheckHideTray))
                .addContainerGap())
        );
        jPanelGeneralPrefsLayout.setVerticalGroup(
            jPanelGeneralPrefsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralPrefsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckDisableTray)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckHideTray)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckUpdates)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelThemes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("pan_themes"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, jPanel1.getFont())); // NOI18N

        jLabel1.setText(bundle.getString("lab_theme")); // NOI18N

        jComboBoxTheme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "System", "Nimbus", "Acryl", "Acryl Green", "Acryl Lemmon", "Acryl Red", "Aero", "Aero Gold", "Aero Green", "Aluminium", "Bernstein", "Mint", "Noire", "HiFi", "McWin", "Smart", "Luna", "Texture", "Graphite" }));
        jComboBoxTheme.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxThemeItemStateChanged(evt);
            }
        });

        jLabel2.setText(bundle.getString("lab_fontsize")); // NOI18N
        jLabel2.setToolTipText(bundle.getString("lab_fontsize")); // NOI18N

        jSpinnerFontSize.setModel(new javax.swing.SpinnerNumberModel(10, 6, 18, 1));

        jCheckWindowDec.setText(bundle.getString("check_windowdec")); // NOI18N
        jCheckWindowDec.setToolTipText(bundle.getString("check_windowdec")); // NOI18N

        javax.swing.GroupLayout jPanelThemesLayout = new javax.swing.GroupLayout(jPanelThemes);
        jPanelThemes.setLayout(jPanelThemesLayout);
        jPanelThemesLayout.setHorizontalGroup(
            jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelThemesLayout.createSequentialGroup()
                        .addComponent(jCheckWindowDec)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelThemesLayout.createSequentialGroup()
                        .addGroup(jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSpinnerFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelThemesLayout.setVerticalGroup(
            jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThemesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelThemesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckWindowDec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancel.setText(bundle.getString("butt_cancel")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonApply.setText(bundle.getString("butt_apply")); // NOI18N
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonApply))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelThemes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelGeneralPrefs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelThemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGeneralPrefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApply)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        updatePreferences();
        doClose(APPLY);
    }//GEN-LAST:event_jButtonApplyActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        doClose(CANCEL);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jComboBoxThemeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxThemeItemStateChanged
        String theme = (String) jComboBoxTheme.getSelectedItem();
        if (gf.isLinux()) {
            jSpinnerFontSize.setEnabled(!theme.contentEquals("System"));
        }
        jCheckWindowDec.setEnabled(!(theme.contentEquals("System") | theme.contentEquals("Nimbus")));
    }//GEN-LAST:event_jComboBoxThemeItemStateChanged

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApply;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JCheckBox jCheckDisableTray;
    private javax.swing.JCheckBox jCheckHideTray;
    private javax.swing.JCheckBox jCheckUpdates;
    private javax.swing.JCheckBox jCheckWindowDec;
    private javax.swing.JComboBox jComboBoxTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGeneralPrefs;
    private javax.swing.JPanel jPanelThemes;
    private javax.swing.JSpinner jSpinnerFontSize;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = CANCEL;
}
