/*
 * Copyright (C) 2007-2013 Alistair Neil, <info@dazzleships.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License Version 2 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package client;

import lib.HashString;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Alistair Neil, <info@dazzleships.net>
 */
public final class SendMailDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form TeleportDialog
     */
    /**
     * @param parent parent frame
     * @param modal whether dialog is modal or not, true means program flow is
     * halted
     */
    public SendMailDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Font fix for text area, essential for crossplatfom look
        jTextAreaBody.setFont(jPanel1.getFont());
        jLabelGold.setVisible(false);
        jSpinAmount.setVisible(false);
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * Set the to descriptor field If param is null use mass mailing else use
     * contents of to field
     *
     * @param to
     * @param hsRace
     */
    public void setToField(String to, HashString hsRace) {
        jComboTo.removeAllItems();
        if (to != null) {
            jComboTo.addItem(to);
            jComboTo.setSelectedIndex(0);
            jComboTo.setEnabled(false);
        } else {
            if (hsRace != null) {
                jComboTo.setModel(new DefaultComboBoxModel(hsRace.getAllValues(false)));
            }
            jComboTo.insertItemAt("Horde", 0);
            jComboTo.insertItemAt("Alliance", 0);
            jComboTo.insertItemAt("All", 0);
            jComboTo.setSelectedIndex(0);
            jComboTo.setEnabled(true);
        }
    }

    public void setToLabel(String text) {
        jLabelTo.setText(text);
    }

    public void setSubjectLabel(String text) {
        jLabelSubject.setText(text);
    }

    public void setBodyLabel(String text) {
        jLabelBody.setText(text);
    }

    public void setGoldLabel(String text) {
        jLabelGold.setText(text);
    }

    public void setContinueButtonText(String text) {
        jButtonContinue.setText(text);
    }

    public void setCancelButtonText(String text) {
        jButtonCancel.setText(text);
    }

    public String getToField() {
        return (String) jComboTo.getSelectedItem();
    }

    /**
     * @return returns the subject contents as a string
     */
    public String getSubject() {
        return jTextSubject.getText();
    }

    /**
     * @return returns the body contents as a string
     */
    public String getBody() {
        return jTextAreaBody.getText();
    }

    /**
     * @return returns amount of money as a string
     */
    public Long getGoldAmount() {
        long lngAmount;
        Long longAmount = (Long) jSpinAmount.getValue();
        lngAmount = longAmount * 10000;
        return lngAmount;
    }

    /**
     * Enabled or Disable the sending of money
     *
     * @param enabled
     */
    public void setGoldEnabled(boolean enabled) {
        jLabelGold.setVisible(enabled);
        jSpinAmount.setVisible(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextSubject = new javax.swing.JTextField();
        jLabelSubject = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelBody = new javax.swing.JLabel();
        jLabelTo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBody = new javax.swing.JTextArea();
        jLabelGold = new javax.swing.JLabel();
        jSpinAmount = new javax.swing.JSpinner();
        jComboTo = new javax.swing.JComboBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("lang/MessagesBundle"); // NOI18N
        setTitle(bundle.getString("title_sendmail")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTextSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubjectActionPerformed(evt);
            }
        });

        jLabelSubject.setFont(jLabelSubject.getFont().deriveFont(jLabelSubject.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelSubject.setText(bundle.getString("lab_subject")); // NOI18N

        jButtonContinue.setText(bundle.getString("butt_send")); // NOI18N
        jButtonContinue.setActionCommand(bundle.getString("butt_continue")); // NOI18N
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        jButtonCancel.setText(bundle.getString("butt_cancel")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelBody.setFont(jLabelBody.getFont().deriveFont(jLabelBody.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelBody.setText(bundle.getString("lab_body")); // NOI18N

        jLabelTo.setFont(jLabelTo.getFont().deriveFont(jLabelTo.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelTo.setText(bundle.getString("lab_to")); // NOI18N

        jTextAreaBody.setColumns(20);
        jTextAreaBody.setLineWrap(true);
        jTextAreaBody.setRows(5);
        jTextAreaBody.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaBody);

        jLabelGold.setFont(jLabelGold.getFont().deriveFont(jLabelGold.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelGold.setText(bundle.getString("lab_gold")); // NOI18N

        jSpinAmount.setFont(jSpinAmount.getFont().deriveFont(jSpinAmount.getFont().getStyle() | java.awt.Font.BOLD));
        jSpinAmount.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(250000L), Long.valueOf(1L)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelGold)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBody, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSubject)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSubject, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonContinue)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTo)
                    .addComponent(jComboTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBody)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelGold)
                    .addComponent(jSpinAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonContinue))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jTextSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubjectActionPerformed
}//GEN-LAST:event_jTextSubjectActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JComboBox jComboTo;
    private javax.swing.JLabel jLabelBody;
    private javax.swing.JLabel jLabelGold;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinAmount;
    private javax.swing.JTextArea jTextAreaBody;
    private javax.swing.JTextField jTextSubject;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
